# Generated by Django 4.0.3 on 2022-04-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_director_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='institute',
        ),
        migrations.AddField(
            model_name='block',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='block', to='api.group'),
        ),
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
