# Generated by Django 4.0.3 on 2022-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_block_institute_block_group_block_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.IntegerField(choices=[(1, '1 курс балавриат'), (2, '2 курс балавриат'), (3, '3 курс балавриат'), (4, '4 курс балавриат'), (5, '1 курс магистратура'), (6, '2 курс магистратура')], default=None),
        ),
        migrations.AddField(
            model_name='institute',
            name='short_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
