# Generated by Django 4.0.3 on 2022-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_course_institute_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='short_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='short_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
